name: Build Docker image and Push to ECR

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The environment we are building"
        required: true
      push:
        type: boolean
        description: "Whether or not we should push the image we build"
        required: true
      tag:
        type: string
        description: "The tag to push to ECR"
        required: true
jobs:
  build_and_deploy:
    name: Docker Build and Push
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE }}
          role-session-name: github-actions
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy data file
        run : |
          cp data/ebbcarbon.yaml dist
          cd dist
          ls -la

      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:dist"
          load: true
          tags: |
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/ebb-${{ vars.ENVIRONMENT }}-resources-lambda:${{ inputs.tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/ebb-${{ vars.ENVIRONMENT }}-resources-lambda:${{ inputs.tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Docker Push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:dist"
          push: ${{ inputs.push }}
          provenance: false
          tags: |
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/ebb-${{ vars.ENVIRONMENT }}-resources-lambda:${{ inputs.tag }}
      - name: Update lambda
        run: |
          IMAGE_URI=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/ebb-${{ vars.ENVIRONMENT }}-resources-lambda:${{ inputs.tag }}
          aws lambda update-function-code --function-name ebb-${{ vars.ENVIRONMENT }}-resources-lambda --image-uri ${IMAGE_URI}


