name: Deploy to production

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: Build and push container image
    uses: ./.github/workflows/build-and-push.yml
    with:
      environment: production
      push: true
      tag: ${{ github.ref_name }}

